<?php define('CORENINPAGE', true);

// This file was generated by ....
// Do not modify it manually. It will be fully regenerated next time....

//define('COREMODULE', 'static');
//define('COREMETHOD', 'main');
//define('COREMMARGS', serialize(array('item'=>'about')));
//define('ENVELOPE'  , 'welcome');
require('./core.php');
//var_dump(get_include_path());

?>