<?php define('COREINPAGE', true);

// This file was generated by ....
// Do not modify it manually. It will be fully regenerated next time....

define('COREMODULE', 'admin_accounts');
define('COREMETHOD', 'main');
define('COREMMARGS', serialize(array('action'=>'confirm')));
require('../../core.php');

?>