<?php define('COREINPAGE', true);

// This file was generated by ....
// Do not modify it manually. It will be fully regenerated next time....

define('COREMODULE', 'forum');
define('COREMETHOD', 'main');
define('COREMMARGS', serialize(array('entity'=>'forum')));
require('../core.php');

?>