<?php define('COREINPAGE', true);

// This file was generated by ....
// Do not modify it manually. It will be fully regenerated next time....

define('COREMODULE', 'doy306_contest');
define('COREMETHOD', 'main');
define('COREMMARGS', serialize(array()));
require('../core.php');

?>