<?php define('COREINPAGE', true);

// This file was generated by ....
// Do not modify it manually. It will be fully regenerated next time....

define('COREMODULE', 'admin_grants');
define('COREMETHOD', 'main');
require('../../core.php');

?>