<?php define('COREINPAGE', true);

// This file was generated by ....
// Do not modify it manually. It will be fully regenerated next time....

define('COREMODULE', 'identify_session');
define('COREMETHOD', 'close');
require('../../core.php');

?>