<?php define('COREINPAGE', true);

// This file was generated by ....
// Do not modify it manually. It will be fully regenerated next time....

define('COREMODULE', 'static');
define('COREMETHOD', 'main'  );
define('COREMMARGS', serialize(array('item'=>'auth')));
require('../core.php');

?>